security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\Person:
          algorithm: auto
    providers:
        person_provider:
            entity:
                class: App\Entity\Person
                property: name
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: person_provider
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\MboAuthenticator
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            remember_me:
              secret: '%kernel.secret%'
              lifetime: 604800
              path: /
            # https://symfony.com/doc/current/security/form_login_setup.html
            logout:
                path: /logout

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
