security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        in_memory: 
            memory:
                users:
                    manager-1-1:
                        password: enter
                        roles: 'ROLE_USER'
        person_provider:
            entity:
                class: App\Entity\Person
                property: name
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: person_provider
            anonymous: ~
            #form_login_ldap:
            simple_form:
                authenticator: App\Security\SolaredgeAuth
                login_path: login
                check_path: login
                #service: Symfony\Component\Ldap\Ldap
            # https://symfony.com/doc/current/security/form_login_setup.html
            logout:
                path: /logout

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
