candidates:
    path: /candidates
    controller: App\Controller\MBOController:candidates
people:
    path: /people/{id}
    controller: App\Controller\MBOController::person_tree
people_admin:
    path: /people_admin
    controller: App\Controller\MBOController:people_admin
year:
    path: /year
    controller: App\Controller\MBOController::by_year
mbo:
    path: /mbo/{year}/{employee}
    controller: App\Controller\MBOController::mbo
