people_root:
    path: /people
    controller: App\Controller\MBOController:root
people:
    path: /people/{id}
    controller: App\Controller\MBOController::index
year:
    path: /year
    controller: App\Controller\MBOController::by_year
