index:
    path: /
    controller: App\Controller\MBOController::by_year
login:
    path: /login
    controller: App\Controller\AuthenticationController::login
logout:
    path: /logout
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
